"""generate C++ golden fixtures for the host test suite.

writes tests/golden/dsp_fixtures.hpp: a few random int16 windows, the python
log-mel spectrograms for each, and peak dbfs values. test_dsp.cpp runs the C++
implementation over the same windows and demands agreement within a tight
float tolerance.
"""
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from features import INFERENCE_WINDOW, log_mel, peak_dbfs  # noqa: E402


def cxx_float_array(name: str, values) -> str:
    def lit(v) -> str:
        s = f"{float(v):.6g}"
        if "e" not in s and "E" not in s and "." not in s:
            s += ".0"          # c++ needs 240.0f, not 240f
        return s + "f"
    vals = ", ".join(lit(v) for v in values)
    return f"inline constexpr float {name}[] = {{ {vals} }};"


def main() -> None:
    rng = np.random.default_rng(1234)
    out = ["// generated by tools/export_fixtures.py — do not edit.",
           "#pragma once", ""]
    cases = []
    for i in range(4):
        # a couple of noisy windows, a couple of quiet ones
        amp = [3000, 300, 8000, 30][i]
        pcm = np.clip(rng.standard_normal(INFERENCE_WINDOW) * amp, -32768, 32767).astype(np.int16)
        spec = log_mel(pcm).ravel()          # band-major, matches C++ layout
        peak = peak_dbfs(pcm)
        n = f"kCase{i}"
        out.append(cxx_float_array(f"{n}_PcmAsFloat", pcm.astype(np.float64)))
        out.append(cxx_float_array(f"{n}_Spec", spec))
        out.append(f"inline constexpr float {n}_PeakDb = {peak:.6g}f;")
        out.append("")
        cases.append(n)
    out.append(f"inline constexpr int kCaseCount = {len(cases)};")
    out.append("inline constexpr int kWindow = 16000;")
    out.append("inline constexpr int kSpecLen = 26 * 61;")
    dest = Path(__file__).parent.parent / "tests" / "golden"
    dest.mkdir(exist_ok=True)
    (dest / "dsp_fixtures.hpp").write_text("\n".join(out) + "\n")
    print(f"wrote {len(cases)} dsp cases")


if __name__ == "__main__":
    main()
