#!/usr/bin/env bash
# copies the trained artifacts into the firmware tree and refreshes the
# decision threshold. run after tools/train.py + tools/export_model.py.
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p firmware/main/model
cp models/detector_int8.onnx firmware/main/model/detector_int8.onnx
THR=${1:-}
python3 - "$THR" <<'EOF'
import json, pathlib, sys
h = json.load(open("models/history.json"))
thr = float(sys.argv[1]) if len(sys.argv) > 1 and sys.argv[1] else h["threshold"]
cfg = pathlib.Path("firmware/main/config.hpp")
cfg.write_text(
    "// generated by tools/sync_model.sh - do not edit by hand.\n"
    f"// validation-fold calibrated point: {h['threshold']:.4f}; live threshold below\n"
    "#pragma once\n"
    f"#define GLASSJAW_THRESHOLD {thr:.4f}f\n"
)
print("threshold:", thr)
EOF
echo "firmware model synced."
