// glassjaw — dsp front end: hamming window, radix-2 fft, htk mel filterbank,
// log-mel spectrogram.
//
// mirrors tools/features.py exactly: same window formula, same fft length,
// same triangle construction, same log floor. tests/test_dsp.cpp pins this
// against golden vectors generated by the python side.
#pragma once

#include <array>
#include <cmath>
#include <cstddef>
#include <span>

#include "pipeline.hpp"

namespace gj {

// symmetric hamming window, identical to numpy.hamming(512).
std::array<float, kFftSize> make_hamming();

// htk-style 26-band mel filterbank over bins 0..256, peak 1.0, no area norm.
// layout: [band][bin], matches mel_filterbank() in python.
std::array<std::array<float, kFftSize / 2 + 1>, kMelBands> make_mel_bank();

// in-place iterative radix-2 fft on interleaved complex floats.
// n must be a power of two. twiddles computed on the fly (rev-bit + butterflies).
void fft(float* re, float* im, std::size_t n);

// one inference window (int16, kWindowSamples) -> log-mel spectrogram
// (kMelBands rows x kFramesPerWindow cols, band-major) + peak level in dbfs.
// band-major order means spec[band * kFramesPerWindow + frame]: the model
// treats the spectrogram as NCHW with C=1, H=bands, W=frames.
struct SpectrogramResult {
  float peak_dbfs;
};

SpectrogramResult log_mel_spectrogram(std::span<const int16_t> window,
                                      std::span<float> spec_out);

// standalone peak level helper (used by the energy gate before anything else).
float peak_dbfs(std::span<const int16_t> window);

}  // namespace gj
